version: '3.7'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword

  minio:
    image: minio/minio:latest
    container_name: "${PROJECT_NAME}_minio"
    volumes:
      - miniodata1:/data1
    #      - data1-2:/data2
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data1
    #    command: server http://minio{1...3}/data{1...2}
    #    command: server http://minio{1...3}/data{1...2} http://minio{4...5}/data{1...4}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

volumes:
  miniodata1: null
  mongodb_data_container: null
